#

queue:
  name: Hosted VS2017
  demands: 
    - npm
    - sh

steps:

  - task: louisgerard.slackposter.slackposterbuild.SlackPoster@0
    inputs:
      UserName: 'VSTS'
      Message: 'Hello World JS build $(Build.BuildID) started'
      ApiToken: '$(Slack.APIToken)'
      Channel: '#rdps-0000-firehose'
        
  - task: Npm@1
    inputs:
      command: custom
      verbose: false
      customCommand: 'install -g yarn gulp'

  - task: ShellScript@2
    inputs:
      scriptPath: './automation/build.sh'
      disableAutoCwd: true
      cwd: '$(System.DefaultWorkingDirectory)'

  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: dist
      includeRootFolder: false
      archiveType: zip
      archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: drop
      ArtifactType: Container

  - task: louisgerard.slackposter.slackposterbuild.SlackPoster@0
    inputs:
      UserName: 'VSTS'
      Message: 'Hello World JS build $(Build.BuildID) finished'
      ApiToken: '$(Slack.APIToken)'
      Channel: '#rdps-0000-firehose'